import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#F4F1ED',
    },
    content: {
      flex: 1,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    backButton: {
      padding: 8,
    },
    closeButton: {
      padding: 8,
    },
    artworkContainer: {
      paddingHorizontal: 32,
      marginBottom: 24,
    },
    artwork: {
      width: '100%',
      aspectRatio: 1,
      borderRadius: 16,
      backgroundColor: '#E8E5E1',
    },
    artworkPlaceholder: {
      backgroundColor: '#E8E5E1',
    },
    infoContainer: {
      paddingHorizontal: 24,
      marginBottom: 32,
    },
    title: {
      fontSize: 20,
      fontWeight: '700',
      color: '#E05F4E',
      marginBottom: 8,
      lineHeight: 26,
    },
    artist: {
      fontSize: 14,
      color: '#8B8680',
      marginBottom: 16,
    },
    statsContainer: {
      marginTop: 8,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    statsContent: {
      flex: 1,
    },
    downloadIconButton: {
      padding: 8,
      marginLeft: 12,
    },
    stat: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 4,
    },
    statEmoji: {
      fontSize: 14,
      marginRight: 6,
    },
    statText: {
      fontSize: 12,
      color: '#8B8680',
    },
    progressContainer: {
      paddingHorizontal: 24,
      marginBottom: 24,
    },
    progressBar: {
      height: 4,
      backgroundColor: '#E8E5E1',
      borderRadius: 2,
      position: 'relative',
      marginVertical: 10,
    },
    progressFill: {
      height: '100%',
      backgroundColor: '#E05F4E',
      borderRadius: 2,
    },
    seekCircle: {
      position: 'absolute',
      top: -8,
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: '#E05F4E',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    timeContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 8,
    },
    timeText: {
      fontSize: 11,
      color: '#8B8680',
    },
    mainControls: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 48,
      marginBottom: 24,
    },
    skipButton: {
      padding: 8,
      position: 'relative',
    },
    skipButtonContent: {
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    skipButtonText: {
      position: 'absolute',
      fontSize: 12,
      fontWeight: '700',
      color: '#403837',
      marginTop: 8,
    },
    playButton: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: '#E05F4E',
      alignItems: 'center',
      justifyContent: 'center',
    },
    downloadContainer: {
      alignItems: 'center',
      marginBottom: 24,
    },
    downloadButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 20,
      borderWidth: 1.5,
      borderColor: '#E05F4E',
    },
    downloadButtonDisabled: {
      opacity: 0.6,
    },
    downloadProgressContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    downloadProgressText: {
      fontSize: 14,
      color: '#E05F4E',
    },
    downloadText: {
      fontSize: 14,
      color: '#E05F4E',
      fontWeight: '600',
    },
    bottomControlsBar: {
      position: 'absolute',
      bottom: 60, // Above Android nav buttons
      left: 24,
      right: 24,
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      backgroundColor: '#403837',
      borderRadius: 30,
      paddingVertical: 12,
      paddingHorizontal: 20,
    },
    bottomControlButton: {
      padding: 8,
      position: 'relative',
    },
    speedText: {
      fontSize: 16,
      color: '#8B8680',
      fontWeight: '600',
    },
    discussionBadge: {
      position: 'absolute',
      top: 2,
      right: 2,
      backgroundColor: '#E05F4E',
      borderRadius: 10,
      minWidth: 18,
      height: 18,
      paddingHorizontal: 4,
      justifyContent: 'center',
      alignItems: 'center',
    },
    badgeText: {
      fontSize: 10,
      color: '#FFFFFF',
      fontWeight: '700',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContent: {
      backgroundColor: '#fff',
      borderRadius: 16,
      padding: 20,
      width: '80%',
      maxWidth: 320,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: '#111827',
      marginBottom: 16,
      textAlign: 'center',
    },
    modalOption: {
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 8,
    },
    modalOptionActive: {
      backgroundColor: '#f3f4f6',
    },
    modalOptionText: {
      fontSize: 16,
      color: '#374151',
      textAlign: 'center',
    },
    modalOptionTextActive: {
      fontWeight: '600',
      color: '#111827',
    },
    // Discussion Full Screen Styles
    miniPlayerOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      zIndex: 1001,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 5,
    },
    discussionPanelOverlay: {
      position: 'absolute',
      top: 0, // Start from top
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 1000,
    },
    discussionMiniPlayer: {
      backgroundColor: '#fff',
      borderBottomWidth: 1,
      borderBottomColor: '#e5e7eb',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 5,
    },
    miniPlayerContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 8,
      height: 64,
    },
    miniPlayerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    miniPlayerArtwork: {
      width: 48,
      height: 48,
      borderRadius: 4,
      backgroundColor: '#e5e7eb',
    },
    miniPlayerInfo: {
      marginLeft: 12,
      flex: 1,
    },
    miniPlayerTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: '#111827',
      marginBottom: 2,
    },
    miniPlayerArtist: {
      fontSize: 12,
      color: '#6b7280',
    },
    miniPlayerPlayButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#f3f4f6',
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: 12,
    },
    miniPlayerProgress: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 2,
      backgroundColor: '#e5e7eb',
    },
    miniPlayerProgressFill: {
      height: 2,
      backgroundColor: '#3b82f6',
    },
    discussionContainer: {
      flex: 1,
      backgroundColor: '#FFFFFF',
    },
    discussionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 20,
      borderBottomWidth: 1,
      borderBottomColor: '#E8E5E1',
    },
    discussionTitle: {
      fontSize: 24,
      fontWeight: '700',
      color: '#403837',
    },
    discussionMessages: {
      flex: 1,
      paddingHorizontal: 20,
      paddingTop: 16,
    },
    discussionItem: {
      flexDirection: 'row',
      marginBottom: 24,
    },
    discussionAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: '#E8E5E1',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    commentAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: '#E05F4E',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    avatarText: {
      fontSize: 14,
      fontWeight: '700',
      color: '#403837',
    },
    discussionMessage: {
      flex: 1,
    },
    discussionAuthor: {
      fontSize: 14,
      fontWeight: '600',
      color: '#403837',
      marginBottom: 4,
    },
    discussionText: {
      fontSize: 14,
      color: '#403837',
      lineHeight: 20,
      marginBottom: 4,
    },
    discussionTime: {
      fontSize: 12,
      color: '#8B8680',
    },
    commentInputContainer: {
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#E8E5E1',
    },
    commentInputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    commentInput: {
      flex: 1,
      backgroundColor: '#F4F1ED',
      borderRadius: 24,
      paddingHorizontal: 20,
      paddingVertical: 12,
    },
    commentInputPlaceholder: {
      fontSize: 14,
      color: '#8B8680',
    },
  });